### ISSUE TITLE
BungeeCord / SubServers support

### ISSUE THREAD

**Issue by samuelh2005** [froggors/SkyBlock-main#3]
Real Hypixel Skyblock is split into multiple sub servers (as seen by the different sever names in the sidebar). Each private island, lobby, etc will be on their own server but connected by BungeeCord (or their own version actually).

They do this because having lots of players spread around multiple servers on multiple machines is less laggy then the same amount of players on one server on multiple worlds. Also it is more reliable because one lobby (out of 10 others) could go down while the others are still playable.

With [SubServers 2](https://github.com/ME1312/SubServers-2) you can dynamically create. delete, or update servers  using the [SubApi](https://github.com/ME1312/SubServers-2/wiki/SubAPI), so private islands, lobbies, etc can be started / stopped when players need them.

Also, MySql / PostgreSQL (preferred) can be used to store statistics, private islands, etc

There should be a config option (somewhere) which allows server owner to enable / disable (BungeeCord / SubServers 2).

This may be challenging to implement, but it will be a fun one?

**Comment by froggors** [comment]
at the moment i am no longer working on this project but i might come back to this in the future for now you are welcome to try doing this yourself if you want to
